#!/bin/bash

if [ "$#" -lt "1" ]; then
	echo "usage: osm4j-extra <class name>"
	exit 1
fi

DIR=$(dirname $0)
LIBS="$DIR/../cli/build/lib-run"

if [ ! -d "$LIBS" ]; then
	echo "Please run 'gradle createRuntime'"
	exit 1
fi

CLASSPATH="$LIBS/*"

exec java -Xmx6g -cp "$CLASSPATH" "$@"
